name: ModelDataManipulator
authors: [DeLson, DeLDev]
description: Allows for ingame query and manipulation of Custom Model Data by players.
main: fun.DeLson.ModelDataManipulator.ModelDataManipulator
version: 1.0
api-version: 1.19

commands:
   model:
      description: Manipulates the custom model data of the item in the player's main hand.
      usage: "Usage: /model [set|get] [optional: model number]"